"""empty message

Revision ID: 8edf8d81fd5c
Revises: ed657e16ce20
Create Date: 2019-04-29 10:12:50.057422

"""

# revision identifiers, used by Alembic.
revision = '8edf8d81fd5c'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
